CREATE TABLE `campaign_details_hourly_billing_v5` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `campaign` int(11) NOT NULL DEFAULT '0',
  `network` int(11) NOT NULL DEFAULT '0',
  `timestamp` datetime NOT NULL,
  `date` date NOT NULL DEFAULT '0000-00-00',
  `month` tinyint(2) NOT NULL DEFAULT '0',
  `hour` int(11) NOT NULL DEFAULT '0',
  `channel` enum('broadcast','wap','web','impression') NOT NULL DEFAULT 'wap',
  `country` int(11) NOT NULL DEFAULT '0',
  `context` enum('mainstream','adult') NOT NULL DEFAULT 'mainstream',
  `product` int(11) NOT NULL DEFAULT '0',
  `aggregator` int(11) NOT NULL DEFAULT '0',
  `endpoint` int(11) NOT NULL DEFAULT '0',
  `service` int(11) NOT NULL DEFAULT '0',
  `publisher` int(11) NOT NULL DEFAULT '0',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'broadcast=0, webad=1',
  `webad` int(11) NOT NULL DEFAULT '0',
  `advertising_campaign` int(11) NOT NULL DEFAULT '0',
  `key_id` int(2) NOT NULL DEFAULT 1,
  `value` decimal(19,4) NOT NULL DEFAULT '0.0000',
  PRIMARY KEY (`id`, `month`),
  KEY `i_advertising_campaign` (`advertising_campaign`, `type_id`, `hour`),
  KEY `i_webad` (`webad`, `type_id`, `hour`),
  KEY `i_campaign` (`campaign`, `network`),
  KEY `i_hourly` (`date`, `hour`, `type`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1
PARTITION BY LIST (`month`) (
  PARTITION p1 VALUES IN (1) ENGINE = InnoDB,
  PARTITION p2 VALUES IN (2) ENGINE = InnoDB,
  PARTITION p3 VALUES IN (3) ENGINE = InnoDB,
  PARTITION p4 VALUES IN (4) ENGINE = InnoDB,
  PARTITION p5 VALUES IN (5) ENGINE = InnoDB,
  PARTITION p6 VALUES IN (6) ENGINE = InnoDB,
  PARTITION p7 VALUES IN (7) ENGINE = InnoDB,
  PARTITION p8 VALUES IN (8) ENGINE = InnoDB,
  PARTITION p9 VALUES IN (9) ENGINE = InnoDB,
  PARTITION p10 VALUES IN (10) ENGINE = InnoDB,
  PARTITION p11 VALUES IN (11) ENGINE = InnoDB,
  PARTITION p12 VALUES IN (12) ENGINE = InnoDB
 )