create table `billing_type` (
    `id` int(11) auto_increment,
    `name` varchar(100) not null,
    `description` varchar(500) null,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

insert into billing_type (`name`) values 
('sms_revenue_1day'),
('sms_revenue_7day'),
('sms_revenue_14day'),
('sms_revenue_15day'),
('sms_revenue_21day'),
('sms_revenue_28day'),
('sms_revenue_30day'),
('sms_revenue_ongoing'),
('sms_maxrevenue_1day'),
('sms_maxrevenue_7day'),
('sms_maxrevenue_14day'),
('sms_maxrevenue_15day'),
('sms_maxrevenue_21day'),
('sms_maxrevenue_28day'),
('sms_maxrevenue_30day'),
('sms_maxrevenue_ongoing'),
('adrevenue_1day'),
('adrevenue_7day'),
('adrevenue_14day'),
('adrevenue_15day'),
('adrevenue_21day'),
('adrevenue_28day'),
('adrevenue_30day'),
('adrevenue_ongoing'),
('adcost_1day'),
('adcost_7day'),
('adcost_14day'),
('adcost_15day'),
('adcost_21day'),
('adcost_28day'),
('adcost_30day'),
('adcost_ongoing'),
('penalties_1day'),
('penalties_7day'),
('penalties_14day'),
('penalties_15day'),
('penalties_21day'),
('penalties_28day'),
('penalties_30day'),
('penalties_ongoing'),
('streaming_1day'),
('streaming_7day'),
('streaming_14day'),
('streaming_15day'),
('streaming_21day'),
('streaming_28day'),
('streaming_30day'),
('streaming_ongoing'),
('cost_other_1day'),
('cost_other_7day'),
('cost_other_14day'),
('cost_other_15day'),
('cost_other_21day'),
('cost_other_28day'),
('cost_other_30day'),
('cost_other_ongoing'),
('signoff_1day'),
('signoff_7day'),
('signoff_14day'),
('signoff_15day'),
('signoff_21day'),
('signoff_28day'),
('signoff_30day'),
('signoff_ongoing'),
('signup_1day'),
('signup_7day'),
('signup_14day'),
('signup_15day'),
('signup_21day'),
('signup_28day'),
('signup_30day'),
('signup_ongoing')
