CREATE TABLE `stop_confirmation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `msisdn` bigint(20) NOT NULL,
  `date` date NOT NULL,
  `month` tinyint(2) NOT NULL DEFAULT month(CURRENT_TIMESTAMP),
  PRIMARY KEY (`id`,`month`),
  KEY `msisdn_date` (`date`,`msisdn`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1
PARTITION BY LIST (`month`) (
  PARTITION p1 VALUES IN (1) ENGINE = InnoDB,
  PARTITION p2 VALUES IN (2) ENGINE = InnoDB,
  PARTITION p3 VALUES IN (3) ENGINE = InnoDB,
  PARTITION p4 VALUES IN (4) ENGINE = InnoDB,
  PARTITION p5 VALUES IN (5) ENGINE = InnoDB,
  PARTITION p6 VALUES IN (6) ENGINE = InnoDB,
  PARTITION p7 VALUES IN (7) ENGINE = InnoDB,
  PARTITION p8 VALUES IN (8) ENGINE = InnoDB,
  PARTITION p9 VALUES IN (9) ENGINE = InnoDB,
  PARTITION p10 VALUES IN (10) ENGINE = InnoDB,
  PARTITION p11 VALUES IN (11) ENGINE = InnoDB,
  PARTITION p12 VALUES IN (12) ENGINE = InnoDB
 )