 CREATE TABLE `subscriptions` (
  `subscription_id` bigint(20) NOT NULL,
  `msisdn` bigint(20) NOT NULL,
  `internal_subscription_id` bigint(20) NOT NULL DEFAULT '0',
  `external_subscription_id` char(80) DEFAULT NULL,
  `customer_id` char(32),
  `company` int(11) NOT NULL DEFAULT '0',
  `product` int(11) NOT NULL DEFAULT '0',
  `country` int(11) NOT NULL DEFAULT '0',
  `endpoint` int(11) NOT NULL DEFAULT '0',
  `network` int(11) NOT NULL DEFAULT '0',
  `context` int(11) NOT NULL DEFAULT '0',
  `service` int(11) NOT NULL DEFAULT '0',
  `datetime_signup` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `datetime_unsubscription` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `datetime_reminder` int(11) NOT NULL DEFAULT '0',
  `datetime_renewal` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `keyword` char(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, 
  `mtn` int(11) NOT NULL DEFAULT '0',
  `advertising_campaign` int(11) NOT NULL DEFAULT '0',
  `project_id` int(11) NOT NULL DEFAULT '0',
  `text_container_id` int(11) NOT NULL DEFAULT '0',
  `session_web` int(11) NOT NULL DEFAULT '0',
  `session_broadcast` int(11) NOT NULL DEFAULT '0',
  `text_counter` int(11) NOT NULL DEFAULT '0',
  `tokens2` int(11) NOT NULL DEFAULT '0',
  `session_value` int(11) NOT NULL DEFAULT '0',
  `session_type` int(11) NOT NULL DEFAULT '0',
  `broadcast_id` int(11) NOT NULL DEFAULT '3',
  `webad` int(11) NOT NULL DEFAULT '0',
  `billing_plan` int(11) NOT NULL DEFAULT '0', 
  `domain_id` int(11) NOT NULL DEFAULT '0',
  `publisher` int(11) NOT NULL DEFAULT '0',
  `affiliate` int(11) NOT NULL DEFAULT '0',
  `bundle` int(11) NOT NULL DEFAULT '0',
  `status_pending` tinyint(4) NOT NULL DEFAULT '0'
  PRIMARY KEY (`subscription_id`),
  UNIQUE KEY `msisdn` (`msisdn`,`company`),
  KEY `country` (`country`,`keyword`),
  KEY `signup` (`signup_datestamp`,`renew_datestamp`),
  KEY `network` (`network`)
) ENGINE=InnoDB AUTO_INCREMENT=68931965 DEFAULT CHARSET=latin1;