SELECT TABLE_SCHEMA, TABLE_NAME, partition_name, PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD
FROM information_schema.PARTITIONS
WHERE TABLE_NAME = 'pixel_registry';

-- ALTER TABLE ads_pixel.pixel_registry TRUNCATE PARTITION p9;


SELECT TABLE_SCHEMA, TABLE_NAME
FROM information_schema.PARTITIONS
where partition_name is not null
group by TABLE_SCHEMA, TABLE_NAME
