SELECT TABLE_SCHEMA, TABLE_NAME, partition_name, PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD
FROM information_schema.PARTITIONS
WHERE PARTITION_ORDINAL_POSITION IS NOT NULL;
-- WHERE TABLE_SCHEMA = 'ads_pixel' AND TABLE_NAME = 'pixel_registry';

-- ALTER TABLE ads_pixel.pixel_registry TRUNCATE PARTITION p9;